package ExceptionHandling;

public class error {
  public static void main(String[] args) {

    // int[] numerator = { 10, 200, 30, 40 };
    // int[] denominator = { 1, 2, 0, 4 };
    // for (int i = 0; i < numerator.length; i++) {
    // System.out.println();
    // }
    // System.out.println("Good job:)");
    // }

    // public static void divide(int a, int b) {
    // try {

    // return;
    // } catch (Exception e) {
    // System.out.println(e);

    // }

  }
}
